// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using OdinCM.Models;

namespace OdinCM.Migrations
{
    [DbContext(typeof(OdinCMContext))]
    partial class OdinCMContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.1.4-rtm-31024");

            modelBuilder.Entity("OdinCM.Models.Article", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<Guid>("AuthorId");

                    b.Property<string>("Content");

                    b.Property<DateTime>("PublishedDateTime")
                        .HasColumnName("Published");

                    b.Property<string>("Slug");

                    b.Property<string>("Topic")
                        .IsRequired()
                        .HasMaxLength(100);

                    b.Property<int>("ViewCount");

                    b.HasKey("Id");

                    b.HasIndex("Slug")
                        .IsUnique();

                    b.ToTable("Articles");

                    b.HasData(
                        new { Id = 1, AuthorId = new Guid("bddf1170-7034-49fa-90d0-3030f45cdfbf"), Content = "This is the default home page. Please change me!", PublishedDateTime = new DateTime(2018, 11, 21, 8, 31, 14, 367, DateTimeKind.Utc), Slug = "home-page", Topic = "HomePage", ViewCount = 0 }
                    );
                });

            modelBuilder.Entity("OdinCM.Models.Comment", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<int?>("ArticleId");

                    b.Property<Guid>("AuthorId");

                    b.Property<string>("Content")
                        .IsRequired();

                    b.Property<string>("DisplayName")
                        .IsRequired()
                        .HasMaxLength(100);

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(100);

                    b.Property<int>("IdArticle");

                    b.Property<DateTime>("SubmittedDateTime")
                        .HasColumnName("Submitted");

                    b.HasKey("Id");

                    b.HasIndex("ArticleId");

                    b.ToTable("Comments");
                });

            modelBuilder.Entity("OdinCM.Models.Customer", b =>
                {
                    b.Property<int>("CustomerID")
                        .ValueGeneratedOnAdd();

                    b.Property<DateTime>("CreatedAtDateTime")
                        .HasColumnName("CreatedAt");

                    b.Property<string>("CustomerName")
                        .IsRequired()
                        .HasMaxLength(100);

                    b.Property<DateTime>("UpdatedAtDateTime")
                        .HasColumnName("UpdatedAt");

                    b.HasKey("CustomerID");

                    b.ToTable("Customer");

                    b.HasData(
                        new { CustomerID = 1, CreatedAtDateTime = new DateTime(2018, 11, 21, 8, 31, 14, 368, DateTimeKind.Utc), CustomerName = "Skf", UpdatedAtDateTime = new DateTime(2018, 11, 21, 8, 31, 14, 368, DateTimeKind.Utc) },
                        new { CustomerID = 2, CreatedAtDateTime = new DateTime(2018, 11, 21, 8, 31, 14, 368, DateTimeKind.Utc), CustomerName = "ABB", UpdatedAtDateTime = new DateTime(2018, 11, 21, 8, 31, 14, 368, DateTimeKind.Utc) },
                        new { CustomerID = 3, CreatedAtDateTime = new DateTime(2018, 11, 21, 8, 31, 14, 368, DateTimeKind.Utc), CustomerName = "Yara", UpdatedAtDateTime = new DateTime(2018, 11, 21, 8, 31, 14, 368, DateTimeKind.Utc) }
                    );
                });

            modelBuilder.Entity("OdinCM.Models.Comment", b =>
                {
                    b.HasOne("OdinCM.Models.Article", "Article")
                        .WithMany("Comments")
                        .HasForeignKey("ArticleId");
                });
#pragma warning restore 612, 618
        }
    }
}
