// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using OdinCM.Data;

namespace OdinCM.Migrations
{
    [DbContext(typeof(OdinCMContext))]
    partial class OdinCMContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.1.4-rtm-31024");

            modelBuilder.Entity("OdinCM.Models.Article", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<Guid>("AuthorId");

                    b.Property<string>("AuthorName")
                        .IsRequired();

                    b.Property<string>("Content");

                    b.Property<DateTime>("PublishedDateTime")
                        .HasColumnName("Published");

                    b.Property<string>("Slug");

                    b.Property<string>("Topic")
                        .IsRequired()
                        .HasMaxLength(100);

                    b.Property<int>("Version");

                    b.Property<int>("ViewCount");

                    b.HasKey("Id");

                    b.HasIndex("Slug")
                        .IsUnique();

                    b.ToTable("Articles");

                    b.HasData(
                        new { Id = 1, AuthorId = new Guid("43c5ac64-0d71-4880-9d38-feefbf2fa277"), AuthorName = "Unknown", Content = "This is the default home page.  Please change me!", PublishedDateTime = new DateTime(2018, 12, 3, 14, 41, 51, 354, DateTimeKind.Utc), Slug = "home-page", Topic = "HomePage", Version = 1, ViewCount = 0 }
                    );
                });

            modelBuilder.Entity("OdinCM.Models.ArticleHistory", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<int>("ArticleId");

                    b.Property<Guid>("AuthorId");

                    b.Property<string>("AuthorName");

                    b.Property<string>("Content");

                    b.Property<DateTime>("PublishedDateTime")
                        .HasColumnName("Published");

                    b.Property<string>("Slug");

                    b.Property<string>("Topic")
                        .IsRequired()
                        .HasMaxLength(100);

                    b.Property<int>("Version");

                    b.HasKey("Id");

                    b.HasIndex("ArticleId");

                    b.ToTable("ArticleHistories");

                    b.HasData(
                        new { Id = 1, ArticleId = 1, AuthorId = new Guid("43c5ac64-0d71-4880-9d38-feefbf2fa277"), AuthorName = "Unknown", Content = "This is the default home page.  Please change me!", PublishedDateTime = new DateTime(2018, 12, 3, 14, 41, 51, 354, DateTimeKind.Utc), Slug = "home-page", Topic = "HomePage", Version = 1 }
                    );
                });

            modelBuilder.Entity("OdinCM.Models.Comment", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<int?>("ArticleId");

                    b.Property<Guid>("AuthorId");

                    b.Property<string>("Content")
                        .IsRequired();

                    b.Property<string>("DisplayName")
                        .IsRequired()
                        .HasMaxLength(100);

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(100);

                    b.Property<int>("IdArticle");

                    b.Property<DateTime>("SubmittedDateTime")
                        .HasColumnName("Submitted");

                    b.HasKey("Id");

                    b.HasIndex("ArticleId");

                    b.ToTable("Comments");
                });

            modelBuilder.Entity("OdinCM.Models.Customer", b =>
                {
                    b.Property<int>("CustomerID")
                        .ValueGeneratedOnAdd();

                    b.Property<DateTime>("CreatedAtDateTime")
                        .HasColumnName("CreatedAt");

                    b.Property<string>("CustomerName")
                        .IsRequired()
                        .HasMaxLength(100);

                    b.Property<DateTime>("UpdatedAtDateTime")
                        .HasColumnName("UpdatedAt");

                    b.HasKey("CustomerID");

                    b.ToTable("Customer");

                    b.HasData(
                        new { CustomerID = 1, CreatedAtDateTime = new DateTime(2018, 12, 3, 14, 41, 51, 366, DateTimeKind.Utc), CustomerName = "Skf", UpdatedAtDateTime = new DateTime(2018, 12, 3, 14, 41, 51, 366, DateTimeKind.Utc) },
                        new { CustomerID = 2, CreatedAtDateTime = new DateTime(2018, 12, 3, 14, 41, 51, 366, DateTimeKind.Utc), CustomerName = "ABB", UpdatedAtDateTime = new DateTime(2018, 12, 3, 14, 41, 51, 366, DateTimeKind.Utc) },
                        new { CustomerID = 3, CreatedAtDateTime = new DateTime(2018, 12, 3, 14, 41, 51, 366, DateTimeKind.Utc), CustomerName = "Yara", UpdatedAtDateTime = new DateTime(2018, 12, 3, 14, 41, 51, 366, DateTimeKind.Utc) },
                        new { CustomerID = 4, CreatedAtDateTime = new DateTime(2018, 12, 3, 14, 41, 51, 366, DateTimeKind.Utc), CustomerName = "Ericsson", UpdatedAtDateTime = new DateTime(2018, 12, 3, 14, 41, 51, 366, DateTimeKind.Utc) }
                    );
                });

            modelBuilder.Entity("OdinCM.Models.SlugHistory", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<DateTime>("AddedDateTime")
                        .HasColumnName("Added");

                    b.Property<int?>("ArticleId");

                    b.Property<string>("OldSlug");

                    b.HasKey("Id");

                    b.HasIndex("ArticleId");

                    b.HasIndex("OldSlug", "AddedDateTime");

                    b.ToTable("SlugHistories");
                });

            modelBuilder.Entity("OdinCM.Models.ArticleHistory", b =>
                {
                    b.HasOne("OdinCM.Models.Article", "Article")
                        .WithMany("History")
                        .HasForeignKey("ArticleId")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("OdinCM.Models.Comment", b =>
                {
                    b.HasOne("OdinCM.Models.Article", "Article")
                        .WithMany("Comments")
                        .HasForeignKey("ArticleId");
                });

            modelBuilder.Entity("OdinCM.Models.SlugHistory", b =>
                {
                    b.HasOne("OdinCM.Models.Article", "Article")
                        .WithMany()
                        .HasForeignKey("ArticleId");
                });
#pragma warning restore 612, 618
        }
    }
}
